
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--]]------------------------------------------------------------------------------


local enums =
{
    ---@class AudioType
     ---@field public UNKNOWN integer
     ---@field public ACC integer
     ---@field public AIFF integer
    ['AudioType'] = {   UNKNOWN=0,  ACC=1,  AIFF=2,  };
    ---@class item.EQuality
     ---@field public WHITE integer @最差品质
     ---@field public BLUE integer @蓝色的
     ---@field public PURPLE integer @紫色的
     ---@field public RED integer @最高品质
    ['item.EQuality'] = {   WHITE=1,  BLUE=2,  PURPLE=3,  RED=4,  };
    ---@class test.AccessFlag
     ---@field public WRITE integer
     ---@field public READ integer
     ---@field public TRUNCATE integer
     ---@field public NEW integer
     ---@field public READ_WRITE integer @位标记使用示例
    ['test.AccessFlag'] = {   WRITE=1,  READ=2,  TRUNCATE=4,  NEW=8,  READ_WRITE=3,  };
}

local beans = {}
    do
    ---@class vec2 
     ---@field public x number
     ---@field public y number
        local class = {
            { name='x', type='number'},
            { name='y', type='number'},
        }
        beans['vec2'] = class
    end
    do
    ---@class vec3 
     ---@field public x number
     ---@field public y number
     ---@field public z number
        local class = {
            { name='x', type='number'},
            { name='y', type='number'},
            { name='z', type='number'},
        }
        beans['vec3'] = class
    end
    do
    ---@class vec4 
     ---@field public x number
     ---@field public y number
     ---@field public z number
     ---@field public w number
        local class = {
            { name='x', type='number'},
            { name='y', type='number'},
            { name='z', type='number'},
            { name='w', type='number'},
        }
        beans['vec4'] = class
    end
    do
    ---@class item.ItemExchange 
     ---@field public id integer @道具id
     ---@field public num integer @道具数量
        local class = {
            { name='id', type='integer'},
            { name='num', type='integer'},
        }
        beans['item.ItemExchange'] = class
    end
    do
    ---@class test.TestExcelBean1  @这是个测试excel结构
     ---@field public x1 integer @最高品质
     ---@field public x2 string @黑色的
     ---@field public x3 integer @蓝色的
     ---@field public x4 number @最差品质
        local class = {
            { name='x1', type='integer'},
            { name='x2', type='string'},
            { name='x3', type='integer'},
            { name='x4', type='number'},
        }
        beans['test.TestExcelBean1'] = class
    end
    do
    ---@class test.TestExcelBean2  @这是个测试excel结构
     ---@field public y1 integer @最高品质
     ---@field public y2 string @黑色的
     ---@field public y3 number @蓝色的
        local class = {
            { name='y1', type='integer'},
            { name='y2', type='string'},
            { name='y3', type='number'},
        }
        beans['test.TestExcelBean2'] = class
    end
    do
    ---@class test.Shape 
        local class = {
        }
        beans['test.Shape'] = class
    end
    do
    ---@class test.Circle :Shape  @这是一个圆
     ---@field public radius number @半径
        local class = {
            { name='radius', type='number'},
        }
        beans['test.Circle'] = class
    end
    do
    ---@class test.Rectangle :Shape  @这是一个矩形
     ---@field public width number @宽度
     ---@field public height number @高度
        local class = {
            { name='width', type='number'},
            { name='height', type='number'},
        }
        beans['test.Rectangle'] = class
    end
    do
    ---@class Room 
     ---@field public max_player_number integer @匹配人数
     ---@field public round_time integer @每局持续
        local class = {
            { name='max_player_number', type='integer'},
            { name='round_time', type='integer'},
        }
        beans['Room'] = class
    end
    do
    ---@class Constant 
     ---@field public room Room
     ---@field public robot_num integer
        local class = {
            { name='room', type='Room'},
            { name='robot_num', type='integer'},
        }
        beans['Constant'] = class
    end
    do
    ---@class Item 
     ---@field public id integer @这是id
     ---@field public name string @名字
     ---@field public desc string @描述
     ---@field public price integer @价格
     ---@field public upgrade_to_item_id integer @引用当前表
     ---@field public expire_time integer @过期时间
     ---@field public batch_useable boolean @能否批量使用
     ---@field public quality integer @品质
     ---@field public exchange_stream item.ItemExchange @道具兑换配置
     ---@field public exchange_list item.ItemExchange[]
     ---@field public exchange_column item.ItemExchange @道具兑换配置
        local class = {
            { name='id', type='integer'},
            { name='name', type='string'},
            { name='desc', type='string'},
            { name='price', type='integer'},
            { name='upgrade_to_item_id', type='integer'},
            { name='expire_time', type='integer'},
            { name='batch_useable', type='boolean'},
            { name='quality', type='integer'},
            { name='exchange_stream', type='item.ItemExchange'},
            { name='exchange_list', type='item.ItemExchange[]'},
            { name='exchange_column', type='item.ItemExchange'},
        }
        beans['Item'] = class
    end

local tables =
{
    { name='TbItem', file='tbitem', mode='map', index='id', value_type='Item' },
    { name='TbConstant', file='tbconstant', mode='one', value_type='Constant'},
}

return { enums = enums, beans = beans, tables = tables }

