--- <auto-generated>
---     Generated by the moonfly tool.  DO NOT EDIT!
--- </auto-generated>

local M={
    C2SLogin = 1,
    S2CLogin = 2,
    C2SMatch = 3,
    C2SEnterRoom = 4,
    C2SMove = 5,
    S2CMatch = 6,
    S2CMatchSuccess = 7,
    S2CEnterRoom = 8,
    S2CMove = 9,
    S2CEnterView = 10,
    S2CLeaveView = 11,
    S2CUpdateRadius = 12,
    S2CDead = 13,
    S2CErrorCode = 14,
    S2CGameOver = 15,
    C2SItemList = 16,
    S2CItemList = 17,
    C2SUseItem = 18,
    S2CUpdateItem = 19,
    C2SHello = 20,
    S2CWorld = 21,
    C2SMailList = 22,
    S2CMailList = 23,
    S2CUpdateMail = 24,
    C2SMailRead = 25,
    C2SMailLock = 26,
    C2SMailReward = 27,
    C2SMailMark = 28,
    C2SMailDel = 29,
    S2CMailDel = 30,
    C2SStartGameLevel = 31,
    S2CStartGameLevel = 32,
    C2SEndGameLevel = 33,
    S2CEndGameLevel = 34,
    C2SUpRoleLevel = 35,
    S2CUpRoleLevel = 36,
    C2SAddAttributePoint = 37,
    S2CAddAttributePoint = 38,
    C2SSellItem = 39,
    S2CSellItem = 40,
    C2SEquipItem = 41,
    S2CEquipItem = 42,
    C2SUnLoadEquipItem = 43,
    S2CUnLoadEquipItem = 44,
    C2SStartProduction = 45,
    C2SSendChat = 46,
    S2CNoticeChat = 47,
    S2CStartProduction = 48,
    C2SReceiveProduction = 49,
    S2CReceiveProduction = 50,
    C2SReceiveTaskReward = 51,
    S2CReceiveTaskReward = 52,
    S2CUpdateTaskInfo = 53,
    C2SGetRanks = 54,
    S2CGetRanks = 55,

}

local forward = {
    C2SLogin = 'addr_user',
    C2SMatch = 'addr_center',
    C2SEnterRoom = 'addr_room',
    C2SMove = 'addr_room',
    C2SItemList = 'addr_user',
    C2SUseItem = 'addr_user',
    C2SHello = 'addr_user',
    C2SMailList = 'addr_mail',
    C2SMailRead = 'addr_mail',
    C2SMailLock = 'addr_mail',
    C2SMailReward = 'addr_mail',
    C2SMailMark = 'addr_mail',
    C2SMailDel = 'addr_mail',
    C2SStartGameLevel = 'addr_user',
    C2SEndGameLevel = 'addr_user',
    C2SUpRoleLevel = 'addr_user',
    C2SAddAttributePoint = 'addr_user',
    C2SSellItem = 'addr_user',
    C2SEquipItem = 'addr_user',
    C2SUnLoadEquipItem = 'addr_user',
    C2SStartProduction = 'addr_user',
    C2SSendChat = 'addr_user',
    C2SReceiveProduction = 'addr_user',
    C2SReceiveTaskReward = 'addr_user',
    C2SGetRanks = 'addr_user',

}

local mt = { forward = forward }

mt.__newindex = function(_, name, _)
    local msg = "attemp index unknown message: " .. tostring(name)
    error(debug.traceback(msg, 2))
end

mt.__index = function(_, name)
    if name == "forward" then
        return forward
    end
    local msg = "attemp index unknown message: " .. tostring(name)
    error(debug.traceback(msg, 2))
end

return setmetatable(M,mt)
